Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/app/urls.py

from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^left/', views.left, name='left'),
    url(r'^grade/', views.grade, name='grade'),
    url(r'^head/', views.head, name='head'),
    url(r'^addgrade/', views.addgrade, name='addgrade'),
    url(r'^student/', views.students, name='student'),
    url(r'^addstu/', views.addstu, name='addstu'),
    url(r'^delstu/', views.delstu, name='delstu'),
    url(r'^editgrade/', views.editgrade, name='editgrade'),

]

Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/day010/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.staticfiles.urls import static

from day010.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls', namespace='app')),
    url(r'^user/', include('user.urls', namespace='user')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)


Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/templates/addgrade.html
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta name="generator" content="" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print" />
<link href="/static/css/print.css" rel="stylesheet" type="text/css"  media="print" />
<script src="/static/js/jquery-1.10.1.min.js"></script>
<script src="/static/js/side.js" type="text/javascript"></script>

<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
</head>

<body>
<!-- Popup -->
<div id="Popup">

<!-- SubPopup -->
<div id="SubPopup">
<script type="text/javascript">
$(function(){
$(".select").each(function(){
var s=$(this);
var z=parseInt(s.css("z-index"));
var dt=$(this).children("dt");
var dd=$(this).children("dd");
var _show=function(){dd.slideDown(200);dt.addClass("cur");s.css("z-index",z+1);};
var _hide=function(){dd.slideUp(200);dt.removeClass("cur");s.css("z-index",z);};
dt.click(function(){dd.is(":hidden")?_show():_hide();});
dd.find("a").click(function(){dt.html($(this).html());_hide();});
$("body").click(function(i){ !$(i.target).parents(".select").first().is(s) ? _hide():"";});})})
</script>
<form action="" method="post">
	{% csrf_token %}
<div class="form_boxC">
<table cellpadding="0" cellspacing="0">
<tr>
<th width="100">班级名称</th>
<td>
<div class="selectbox" style="width:230px;">
	<input type="hidden" name="grade_id" value="{{ grade_id }}">
	<input type="text" name="grade_name" placeholder="请填入班级名称">
</div>
</td>
</tr>

</table>
<div id="BtmBtn">
<div class="btn_box floatR">
	<input name="" type="submit" value="提交">
</div>
</div>
</div>
</form>
</div>
<!-- SubPopup -->


</div>
<!-- /Popup -->
</body>
</html>

Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/templates/addstu.html
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta name="generator" content="" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print" />
<link href="/static/css/print.css" rel="stylesheet" type="text/css"  media="print" />
<script src="/static/js/jquery-1.10.1.min.js"></script>
<script src="/static/js/side.js" type="text/javascript"></script>

</head>

<body>
<!-- Popup -->
<div id="Popup">

<!-- SubPopup -->
<div id="SubPopup">
<script type="text/javascript">
$(function(){
$(".select").each(function(){
var s=$(this);
var z=parseInt(s.css("z-index"));
var dt=$(this).children("dt");
var dd=$(this).children("dd");
var _show=function(){dd.slideDown(200);dt.addClass("cur");s.css("z-index",z+1);};
var _hide=function(){dd.slideUp(200);dt.removeClass("cur");s.css("z-index",z);};
dt.click(function(){dd.is(":hidden")?_show():_hide();});
dd.find("a").click(function(){dt.html($(this).html());_hide();});
$("body").click(function(i){ !$(i.target).parents(".select").first().is(s) ? _hide():"";});})})
</script>
<div class="form_boxC">
<p>"<span class="f_cB">*</span>"号为必填项目</p>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
<table cellpadding="0" cellspacing="0">
<tr>
<th>姓名 <span class="f_cB">*</span></th>
<td>
    <div class="txtbox floatL" style="width:150px;">
        <input style="width:150px;" name="s_name" type="text" size="5" placeholder="请输入学生姓名">
    </div>
</td>
</tr>
<tr>
    <th>头像</th>
    <td>
        <div class="txtbox floatL" style="width:150px;">
            <input type="file" name="s_img">
        </div>
    </td>
</tr>

<tr>
<th>所属班级<span class="f_cB">*</span></th>
<td><!-- selectbox -->
<div class="selectbox" style="width:230px;">
    <select name="g_id">
        {% for grade in grades %}
            <option value="{{ grade.id }}">{{ grade.g_name }}</option>
        {% endfor %}
    </select>
</div>
</td>
</tr>

</table>
<div id="BtmBtn">
<div class="btn_box floatR"><input name="" type="submit" value="提交"></div>
</div>
</form>
</div>
</div>
</div>
</body>
</html>

Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/templates/changepwd.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>修改密码</title>
<link rel="stylesheet" type="text/css" href="css/css.css" />
<script type="text/javascript" src="js/jquery.min.js"></script>
</head>
<body>
	<div id="pageAll">
		<div class="pageTop">
			<div class="page">
				<img src="img/coin02.png" /><span><a href="#">首页</a>&nbsp;-&nbsp;<a
					href="#">公共管理</a>&nbsp;-</span>&nbsp;修改密码
			</div>
		</div>
		<div class="page ">
			<!-- 修改密码页面样式 -->
			<div class="bacen">
				<div class="bbD">
					&nbsp;&nbsp;&nbsp;&nbsp;管理员UID：&nbsp;&nbsp;&nbsp;&nbsp;123</div>
				<div class="bbD">管理员用户名：&nbsp;&nbsp;&nbsp;&nbsp;123456789</div>
				<div class="bbD">
					&nbsp;&nbsp;&nbsp;&nbsp;输入旧密码：<input type="password" class="input3"
						onblur="checkpwd1()" id="pwd1" /> <img class="imga"
						src="img/ok.png" /><img class="imgb" src="img/no.png" />
				</div>
				<div class="bbD">
					&nbsp;&nbsp;&nbsp;&nbsp;输入新密码：<input type="password" class="input3"
						onblur="checkpwd2()" id="pwd2" /> <img class="imga"
						src="img/ok.png" /><img class="imgb" src="img/no.png" />
				</div>
				<div class="bbD">
					再次确认密码：<input type="password" class="input3" onblur="checkpwd3()"
						id="pwd3" /> <img class="imga" src="img/ok.png" /><img
						class="imgb" src="img/no.png" />
				</div>
				<div class="bbD">
					<p class="bbDP">
						<button class="btn_ok btn_yes" href="#">提交</button>
						<a class="btn_ok btn_no" href="#">取消</a>
					</p>
				</div>
			</div>

			<!-- 修改密码页面样式end -->
		</div>
	</div>
</body>
<script type="text/javascript">
function checkpwd1(){
var user = document.getElementById('pwd1').value.trim();
 if (user.length >= 6 && user.length <= 12) {
  $("#pwd1").parent().find(".imga").show();
  $("#pwd1").parent().find(".imgb").hide();
 }else{
  $("#pwd1").parent().find(".imgb").show();
  $("#pwd1").parent().find(".imga").hide();
 };
}
function checkpwd2(){
var user = document.getElementById('pwd2').value.trim();
 if (user.length >= 6 && user.length <= 12) {
  $("#pwd2").parent().find(".imga").show();
  $("#pwd2").parent().find(".imgb").hide();
 }else{
  $("#pwd2").parent().find(".imgb").show();
  $("#pwd2").parent().find(".imga").hide();
 };
}
function checkpwd3(){
var user = document.getElementById('pwd3').value.trim();
var pwd = document.getElementById('pwd2').value.trim();
 if (user.length >= 6 && user.length <= 12 && user == pwd) {
  $("#pwd3").parent().find(".imga").show();
  $("#pwd3").parent().find(".imgb").hide();
 }else{
   $("#pwd3").parent().find(".imgb").show();
  $("#pwd3").parent().find(".imga").hide();
 };
}
</script>
</html>

Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/templates/grade.html
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta name="generator" content="" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print" />
<link href="/static/css/print.css" rel="stylesheet" type="text/css"  media="print" />
<script src="/static/js/jquery-1.10.1.min.js"></script>
<script src="/static/js/side.js" type="text/javascript"></script>

<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
</head>

<body>


<!-- MainForm -->
<div id="MainForm">
<div class="form_boxA">
<h2>班级信息列表</h2>
<table cellpadding="0" cellspacing="0">
<tr>
<th>序号</th>
<th>班级名称</th>
<th>创建时间</th>
<th>操作</th>
</tr>
    {% for page in pages %}
    <tr>
        <td>{{ page.id }}</td>
        <td>{{ page.g_name|upper }}</td>
        <td>{{ page.g_create_time|date:'Y-m-d h:m:s' }}</td>
        <td><a href="{% url 'app:editgrade' %}?grade_id={{ page.id }}">编辑</a></td>
    </tr>
    {% endfor %}

</table>
<p class="msg">共找到47条年度预算记录，当前显示从第1条至第10条</p>
</div>

<ul id="PageNum">
<li><a href="{% url 'app:grade' %}">首页</a></li>
    {% if pages.has_previous %}
        <li><a href="{% url 'app:grade' %}?page_num={{ pages.previous_page_number }}">上一页</a></li>
    {% endif %}
    {% for i in pages.paginator.page_range %}
        <li><a href="{% url 'app:grade' %}?page_num={{ i }}">{{ i }}</a></li>
    {% endfor %}
    {% if pages.has_next %}
        <li><a href="{% url 'app:grade' %}?page_num={{ pages.next_page_number }}">下一页</a></li>
    {% endif %}
<li>当前{{ pages.number }}页</li>
<li><a href="{% url 'app:grade' %}?page_num={{ pages.paginator.num_pages }}">尾页</a></li>
</ul>

</div>

</body>
</html>

Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/templates/head.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>头部</title>
<link rel="stylesheet" type="text/css" href="/static/css/public.css" />
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/public.js"></script>
</head>

<body>
	<!-- 头部 -->
	<div class="head">
		<div class="headL">
			<img class="headLogo" src="/static/img/logLOGO.png"/>
		</div>
		<div class="headR">
			<span style="color:#FFF">欢迎：admin</span> <a href="head2.html" rel="external">【退出】</a>
		</div>
	</div>
</body>
</html>

Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/templates/head2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>头部-有点</title>
<link rel="stylesheet" type="text/css" href="css/public.css" />
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/public.js"></script>
</head>

<body>
	<!-- 头部 -->
	<div class="head">
		<div class="headL">
			<img class="headLogo" src="img/logLOGO.png"/>
		</div>
		<div class="headR">
			<span style="color:#FFF"><a href="login.html" target="_blank">【登录】</a></span> 
		</div>
	</div>
</body>
</html>

Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>首页</title>
</head>
<frameset rows="100,*" cols="*" scrolling="No" framespacing="0"
	frameborder="no" border="0">
	<frame src="{% url 'app:head' %}" name="headmenu" id="mainFrame" title="mainFrame"><!-- 引用头部 -->
<!-- 引用左边和主体部分 -->
	<frameset rows="100*" cols="220,*" scrolling="No"
	framespacing="0" frameborder="no" border="0">
		<frame src="{% url 'app:left' %}" name="leftmenu" id="mainFrame" title="mainFrame">
		<frame src="{% url 'app:grade' %}" name="main" scrolling="yes" noresize="noresize"
	id="rightFrame" title="rightFrame">
	</frameset>
</frameset>
</html>

Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/templates/left.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>首页左侧导航</title>
<link rel="stylesheet" type="text/css" href="/static/css/public.css" />
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/public.js"></script>
<head></head>

<body id="bg">
	<!-- 左边节点 -->
	<div class="container">

		<div class="leftsidebar_box">
			<a href="main.html" target="main"><div class="line">
					<img src="/static/img/coin01.png" />&nbsp;&nbsp;首页
				</div></a>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="/static/img/coin03.png" /><img class="icon2"
						src="/static/img/coin04.png" /> 班级管理<img class="icon3"
						src="/static/img/coin19.png" /><img class="icon4"
						src="/static/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" />
					<a class="cks" href="{% url 'app:grade' %}"
						target="main">班级列表</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" />
					<a class="cks" href="{% url 'app:addgrade' %}"
						target="main">班级添加</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="/static/img/coin03.png" /><img class="icon2"
						src="/static/img/coin04.png" /> 学生管理<img class="icon3"
						src="/static/img/coin19.png" /><img class="icon4"
						src="/static/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" />
					<a class="cks" href="{% url 'app:student' %}"
						target="main">学生列表</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" />
					<a class="cks" href="{% url 'app:addstu' %}"
						target="main">添加学生</a><img class="icon5" src="/static/img/coin21.png" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="/static/img/coinL1.png" /><img class="icon2"
						src="/static/img/coinL2.png" /> 系统管理<img class="icon3"
						src="/static/img/coin19.png" /><img class="icon4"
						src="/static/img/coin20.png" />
				</dt>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a href="changepwd.html"
						target="main" class="cks">修改密码</a><img class="icon5"
						src="/static/img/coin21.png" />
				</dd>
				<dd>
					<img class="coin11" src="/static/img/coin111.png" /><img class="coin22"
						src="/static/img/coin222.png" /><a class="cks">退出</a><img
						class="icon5" src="/static/img/coin21.png" />
				</dd>
			</dl>

		</div>

	</div>
</body>
</html>

Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>登录</title>
<link rel="stylesheet" type="text/css" href="/static/css/public.css" />
<link rel="stylesheet" type="text/css" href="/static/css/page.css" />
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/public.js"></script>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
	<!-- 登录body -->
	<div class="logDiv">
		<img class="logBanner" src="/static/img/logBanner.png" />
		<div class="logGet">
			<!-- 头部提示信息 -->
			<div class="logD logDtip">
				<p class="p1">登录</p>
			</div>
            {{ msg }}
			<!-- 输入框 -->
			<div class="lgD">
				<img class="img1" src="/static/img/logName.png" />
                <input type="text" name="username" placeholder="输入用户名" />
			</div>
			<div class="lgD">
				<img class="img1" src="/static/img/logPwd.png" />
                <input type="text" name="password" placeholder="输入用户密码" />
			</div>
			<div class="logC">
				<button>
                    <input type="submit" value="登 录">
                </button>
			</div>
		</div>
	</div>
	<!-- 登录body  end -->
</form>
	<!-- 登录页面底部 -->
	<div class="logFoot">
		<p class="p1">版权所有：安徽公司公司</p>
		<p class="p2">123456789</p>
	</div>
	<!-- 登录页面底部end -->
   
</body>
</html>

Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/templates/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>注册</title>
<link rel="stylesheet" type="text/css" href="/static/css/public.css" />
<link rel="stylesheet" type="text/css" href="/static/css/page.css" />
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/public.js"></script>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
	<!-- 登录body -->
	<div class="logDiv">
		<img class="logBanner" src="/static/img/logBanner.png" />
		<div class="logGet">
			<!-- 头部提示信息 -->
			<div class="logD logDtip">
				<p class="p1">注 册</p>
			</div>
            {{ msg }}
			<!-- 输入框 -->
			<div class="lgD">
				<img class="img1" src="/static/img/logName.png" />
                <input type="text" name="username" placeholder="输入用户名" />
			</div>
			<div class="lgD">
				<img class="img1" src="/static/img/logPwd.png" />
                <input type="text" name="pwd1" placeholder="输入用户密码1" />
			</div>
            <div class="lgD">
				<img class="img1" src="/static/img/logPwd.png" />
                <input type="text" name="pwd2" placeholder="输入用户密码2" />
			</div>
			<div class="logC">
				<button>
                    <input type="submit" value="注 册">
                </button>
			</div>
		</div>
	</div>
	<!-- 登录body  end -->
</form>
	<!-- 登录页面底部 -->
	<div class="logFoot">
		<p class="p1">版权所有：安徽公司公司</p>
		<p class="p2">123456789</p>
	</div>
	<!-- 登录页面底部end -->

</body>
</html>

Lecture notes/web框架/django/wang/day02(中间件:登录注册,文件)/templates/student.html
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta name="generator" content="" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print" />
<link href="/static/css/print.css" rel="stylesheet" type="text/css"  media="print" />
<script src="/static/js/jquery-1.10.1.min.js"></script>
<script src="/static/js/side.js" type="text/javascript"></script>

<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
</head>

<body>


<!-- MainForm -->
<div id="MainForm">
<div class="form_boxA">
<h2>学生信息列表</h2>
<table cellpadding="0" cellspacing="0">
<tr>
<th>序号</th>
<th>学生名称</th>
<th>班级</th>
<th>头像</th>
<th>操作</th>
</tr>
    {% for stu in pages %}
    <tr>
        <td>{{ stu.id }}</td>
        <td>{{ stu.s_name }}</td>
        <td>{{ stu.g.g_name }}</td>
        <td><img src="/media/{{ stu.s_img }}" width="100" height="100"></td>
        <td><a href="{% url 'app:delstu' %}?s_id={{ stu.id }}">删除</a></td>
    </tr>
    {% endfor %}

</table>
<p class="msg">共找到47条年度预算记录，当前显示从第1条至第10条</p>
</div>

<ul id="PageNum">
<li><a href="{% url 'app:student' %}">首页</a></li>
    {% if pages.has_previous %}
        <li><a href="{% url 'app:student' %}?page_num={{ pages.previous_page_number }}">上一页</a></li>
    {% endif %}
    {% for i in pages.paginator.page_range %}
        <li><a href="{% url 'app:student' %}?page_num={{ i }}">{{ i }}</a></li>
    {% endfor %}
    {% if pages.has_next %}
        <li><a href="{% url 'app:student' %}?page_num={{ pages.next_page_number }}">下一页</a></li>
    {% endif %}
<li><a href="{% url 'app:student' %}?page_num={{ pages.paginator.num_pages }}">尾页</a></li>
</ul>

</div>

</body>
</html>