爱鲜蜂项目/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    # 主页
    url(r'^home/', views.home, name='home'),
    # 个人中心
    url(r'^mine/', views.mine, name='mine'),

    # 购物车
    url(r'^cart/', views.cart, name='cart'),
    # 闪购
    url(r'^market/$', views.market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.user_market, name='user_market'),

    # 添加购物车
    url(r'^addCart/', views.addCart, name='addCart'),
    # 删除购物车
    url(r'^delCart/', views.delCart, name='delCart'),

    # 改变购物车里面的状态(钩钩xx)
    url(r'^changeCartState/', views.changeCartState, name='changeCartState'),
    # 全选
    url(r'^selectAll/', views.selectAll, name='selectAll'),
    # 取消全选
    url(r'^clearAll/', views.clearAll, name='clearAll'),
    # 购物车页面get请求时自动加载总价
    url(r'^showMoney/', views.showMoney),

    # 下单
    url(r'^pay/', views.pay, name='pay'),
    # 支付
    url(r'^alipay/', views.alipay, name='alipay'),
    # 代付款
    url(r'^orderListWaitPay/', views.orderListWaitPay, name='orderListWaitPay'),
    # 待收货
    url(r'^orderListPayed/', views.orderListPayed, name='orderListPayed'),

    # 代付款 待收货 的付款收货
    url(r'^waitPay/(\d+)/', views.waitPay, name='waitPay'),
    url(r'^confirmGoods/(\d+)/', views.confirmGoods, name='confirmGoods'),
]

爱鲜蜂项目/axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from axf.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='app')),
    url(r'^user/', include('user.urls', namespace='user'))
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

爱鲜蜂项目/app/models.py
from django.db import models

from user.models import UserModel


class Main(models.Model):
    img = models.CharField(max_length=200)
    name = models.CharField(max_length=100)
    trackid = models.CharField(max_length=16)  #订单编号

    class Meta:
        abstract = True


#轮播
class MainWheel(Main):
    class Meta:
        db_table = "axf_wheel"


#导航
class MainNav(Main):
    class Meta:
        db_table = "axf_nav"


# 必购
class MainMustBuy(Main):
    class Meta:
        db_table = 'axf_mustbuy'


# 商店
class MainShop(Main):
    class Meta:
        db_table = 'axf_shop'


# 主页展示
class MainShow(Main):
    categoryid = models.CharField(max_length=16)  # category分类
    brandname = models.CharField(max_length=100)    # brand品牌

    img1 = models.CharField(max_length=200)
    childcid1 = models.CharField(max_length=16)
    productid1 = models.CharField(max_length=16)
    longname1 = models.CharField(max_length=100)
    price1 = models.FloatField(default=0)
    marketprice1 = models.FloatField(default=1)

    img2 = models.CharField(max_length=200)
    childcid2 = models.CharField(max_length=16)
    productid2 = models.CharField(max_length=16)
    longname2 = models.CharField(max_length=100)
    price2 = models.FloatField(default=0)
    marketprice2 = models.FloatField(default=1)

    img3 = models.CharField(max_length=200)
    childcid3 = models.CharField(max_length=16)
    productid3 = models.CharField(max_length=16)
    longname3 = models.CharField(max_length=100)
    price3 = models.FloatField(default=0)
    marketprice3 = models.FloatField(default=1)

    class Meta:
        db_table = 'axf_mainshow'


#食物分类
class FoodType(models.Model):
    typeid = models.CharField(max_length=16)
    typename = models.CharField(max_length=100)
    childtypenames = models.CharField(max_length=200)
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = "axf_foodtypes"


# 商品类
class Goods(models.Model):
    productid = models.CharField(max_length=16)
    productimg = models.CharField(max_length=200) #商品图片
    productname = models.CharField(max_length=100) #商品名称
    productlongname = models.CharField(max_length=200)
    isxf = models.IntegerField(default=1)
    pmdesc = models.CharField(max_length=100)
    specifics = models.CharField(max_length=100)
    price = models.FloatField(default=0)        #现价
    marketprice = models.FloatField(default=1)  #商场价
    categoryid = models.CharField(max_length=16) #左侧分类id
    childcid = models.CharField(max_length=16) #全部分类下面的子分类
    childcidname = models.CharField(max_length=100)
    dealerid = models.CharField(max_length=16)
    storenums = models.IntegerField(default=1)
    productnum = models.IntegerField(default=1)  #销量

    class Meta:
        db_table = "axf_goods"


class CartModel(models.Model):    # 购物车
    user = models.ForeignKey(UserModel)  # 关联用户
    goods = models.ForeignKey(Goods)    # 关联商品
    c_num = models.IntegerField(default=1)  # 商品个数
    is_select = models.BooleanField(default=True)   # 是否选择商品

    class Meta:
        db_table = 'axf_cart'


class OrderModel(models.Model):    # 订单
    user = models.ForeignKey(UserModel)  # 关联的用户
    o_num = models.CharField(max_length=64)  # 订单号
    # 0 代表已下单，未付款， 1已付款未发货， 2已付款已发货
    o_status = models.IntegerField(default=0)  # 状态
    o_create = models.DateTimeField(auto_now_add=True)  # 创建时间

    class Meta:
        db_table = 'axf_order'


class OrderGoodsModel(models.Model):
    goods = models.ForeignKey(Goods)  # 关联的商品
    order = models.ForeignKey(OrderModel)  # 关联的订单
    goods_num = models.IntegerField(default=1)  # 商品的个数

    class Meta:
        db_table = 'axf_order_goods'

爱鲜蜂项目/templates/order/order_info.html
{% extends 'base.html' %}
{% load static %}

{% block EXTJS %}
    <script type="text/javascript" src="{% static 'app/order/js/order.js' %}"></script>
    <script src="{% static 'common/functions.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="order_info" class="container">
        {% csrf_token %}
    <!--订单编号-->
    <h3>订单编号:{{ order.o_num }}</h3>
    <!--处理结束-->
    <ul>

        <!--所有订单信息展示-->
        {% for i in order.ordergoodsmodel_set.all %}
            <li>
                <!--商品名称展示-->
                <img src="{{ i.goods.productimg }}">

                <span>{{ i.goods_num }}</span>
            </li>
        {% endfor %}
        <!--订单处理结束-->

    </ul>
        <!--订单id展示-->
        <button class="btn btn-success btn-block" onclick="alipay({{ order.id }})">Alipay</button>

    </div>


{% endblock %}

爱鲜蜂项目/templates/order/order_list_payed.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待收货订单列表</h3>

    <ul>
        <!--订单信息展示-->
            {% for i in user_orders %}
            <li>
                <a href="">订单号:{{ i.o_num }}</a>
                <p><a href="{% url 'app:confirmGoods' i.id %}">确认收货</a></p>

                        <!--展示商品的名称-->
                        {% for j in i.ordergoodsmodel_set.all %}
                        <li class="foo">
                        <h6>{{ j.goods.productlongname }}</h6>
                            <img style="height: 100px; width: 100px" src="{{ j.goods.productimg }}" alt="">
                            <p>数量:{{ j.goods_num }}</p>
                        </li>
                        {% endfor %}
                        <!--处理结束-->
                <hr>
            </li>
            {% endfor %}
        <!--订单处理结束-->
    </ul>


{% endblock %}

爱鲜蜂项目/templates/order/order_list_wait_pay.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h3>待付款订单列表</h3>

    <ul>
        <!--订单信息展示-->
            {% for i in user_orders %}
            <li>
                <a href="">订单号:{{ i.o_num }}</a>
                <p><a href="{% url 'app:waitPay' i.id%}">确认付款</a></p>

                        <!--展示商品的名称-->
                        {% for j in i.ordergoodsmodel_set.all %}
                        <li class="foo">
                            <h6>{{ j.goods.productlongname }}</h6>
                            <img style="height: 100px; width: 100px" src="{{ j.goods.productimg }}" alt="">
                            <p>数量:{{ j.goods_num }}</p>

                        </li>
                        {% endfor %}
                        <!--处理结束-->
                <hr>
            </li>
            {% endfor %}
        <!--订单处理结束-->
    </ul>


{% endblock %}